### ISSUE TITLE
Adjust canvas size inside text editor and put focus in the begining of text when access the page

### ISSUE THREAD

**Issue by tiagosoares94** [renatoliveira/notto#17]
Now, when you access a page, you can start typing only if you click on the green area. If you click outside the area, nothing happens and you can't type.
![image](https://user-images.githubusercontent.com/28827228/33791847-fcc58654-dc79-11e7-8cd1-daa5c600ba3a.png)

**Comment by renatoliveira** [comment]
Fixed with d2645fde94cabdb228a9d18e119e746d72b88502.
