### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mohammadhsn** [renatoliveira/notto#37]
I forked the repository and I tried to install it on my local.
I passed installation steps according to `README.md`.
When I ran `python manage.py migrate` an exception raised!
The problem is Django doesn't know where our settings file is!

I changed `manage.py` file and the problem solved!

The default settings file can be defined in `DJANGO_SETTINGS_MODULE` environment variable, but I think it's better to set the default settings in `manage.py`.

If you agree with me, I'll send pull request :)

**Comment by renatoliveira** [comment]
What kind of exception you got? What did you do to manage.py to fix it?

Assuming you are on Windows, I think you ran into the issue of Django not loading the settings properly. If you take a look at the makefile you can see how to use the `--settings` option to manage.py. 

Let me know if that's the issue! I think it is best if I add this little part to the readme...

**Comment by mohammadhsn** [comment]
The error is:
`django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.`
It is obvious because Django doesn't know about settings file and also secret key!

I'm not on windows :) I'm on Ubuntu.

I changed `manage.py`, see [this commit](https://github.com/mohammadh73/notto/commit/f566a2a0be23e5e2546529b51024770251b5fd62)

yes, it works with `--settings`, but I think it's better to have default settings file to prevent exception.

Notice that `--settings` flag still works and it overrides `manage.py` settings file.

I don`t think so that we need to add something to the Readme file.

Would you like to merge my small change?

**Comment by renatoliveira** [comment]
Sounds good to me. Do it. 👍

**Comment by renatoliveira** [comment]
Closed with #38.
