### ISSUE TITLE
Option to save the text area in pdf format

### ISSUE THREAD

**Issue by tiagosoares94** [renatoliveira/notto#8]

**Comment by alexNeto-zz** [comment]
I can do that, if you want

**Comment by renatoliveira** [comment]
That would be great, @alexNeto. Just make a PR when ready 😉

**Comment by alexNeto-zz** [comment]
alright, but I'm having trouble with the dev environment, I can't open a note.
Should I open a new issue?

**Comment by renatoliveira** [comment]
Have you set `DEBUG = True` in `settings.py`?

**Comment by alexNeto-zz** [comment]
now I did, thank you

**Comment by renatoliveira** [comment]
Added with 1ba08f7c9779e2acb20f6f1651ec70377669c3ef. Thank you Alexandre. 👍

I strongly recommend you to use pylint next time though! 😜 Some imports were unnecessary, some variables weren't used.

You mentioned in #25 that there's an issue with Slavic characters. If you can, please open an issue for that as well. We are going to look into that in the near future.

**Comment by alexNeto-zz** [comment]
sorry, I'm used to ctrl+shift+o from eclipse
