### ISSUE TITLE
Ability to create nested folders using '/'

### ISSUE THREAD

**Issue by tiagosoares94** [renatoliveira/notto#9]
Example:
notto.io/tiago/folder1

**Comment by renatoliveira** [comment]
@filipemeneses please help me with your JS code used on the note template. When I tested an access to `/foo/bar` in my local machine I got a POST to `/foo/foo/bar` instead. Checkout the `dev` branch to your machine and take a look and please confirm if this is a front-end issue or a back-end one. 😄 

Here is the log of opening `/foo/bar/` and typing something on the editor.

```
(nottoenv) λ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
December 10, 2017 - 15:45:31
Django version 2.0, using settings 'notto.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
<QuerySet []>
[10/Dec/2017 15:45:31] "GET /foo/bar HTTP/1.1" 200 3983
<QuerySet []>
[10/Dec/2017 15:45:34] "POST /foo/foo/bar HTTP/1.1" 200 4040
```

**Comment by filipemeneses** [comment]
@renatoliveira It's a front-end issue. I'm using the `note_url` directly, building the URL will fix it:

Changing 
```
http.open("POST", url, true);
``` 
to
```
http.open("POST", window.location.origin + '/' + url, true);
```
will work.

**Comment by renatoliveira** [comment]
Added feature with dc711077ab98fb2640eabbc92e77f1e7c71b2bc1. @filipemeneses Thanks
